### ISSUE TITLE
How can I open it 

### ISSUE THREAD

**Issue by RoyXu93** [RechargedGreen/RRPathVisualizer#1]
I know it is a useful tool for creat a path.  I want to use it but I am rookie about how to use it, I can't open it even.  Would it be ok if I ask you to give me some tips or links to help me.

**Comment by msms007** [comment]
It would be really helpful if could add some guide on how to configure and run RRPathVisualizer.

**Comment by Aman-Anas** [comment]
Yeah some documentation would be nice

**Comment by richpant** [comment]
I know in learnroadrunner there is a small tutorial. https://www.learnroadrunner.com/tool/rrpathvisualizer.html, but I still can not get it to work? I try to run the example and get an error "4:06 PM	Error running 'AppKt': Class 'AppKt' not found in module 'RRPathVisualizer-master'"

**Comment by mohanskumar** [comment]
installed JDK 15 ( the latest) and receiving the same error too Error running 'AppKt': Class 'AppKt' not found in module 'RRPathVisualizer'"

**Comment by msms007** [comment]
I had the similar problem. It started working after updating the config. ( attached pic)
![image](https://user-images.githubusercontent.com/4041250/96632778-32439500-12e6-11eb-8f5e-399b67b30964.png)
