### ISSUE TITLE
multiple trajectories end location

### ISSUE THREAD

**Issue by lmgutman** [RechargedGreen/RRPathVisualizer#7]
I tried to follow the video here https://youtu.be/70mOwbp6ANs about adding multiple trajectories and using the end values from the last trajectories, but I can't make it work. it says the end() method can't be resolved. 

Any ideas?

**Comment by lmgutman** [comment]
figured it out by finding other examples.

**Comment by NoahBres** [comment]
For future reference, you can refer to https://www.learnroadrunner.com/trajectories.html#running-multiple-trajectories for more examples/documentation.
